import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import { Toaster } from "react-hot-toast";
import TranstackQueryProvider from "@/providers/tanstack-query-provider";
import ReduxProvider from "@/lib/ReduxProvider";
import StoreUser from '@/components/StoreUser'
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranstackQueryProvider>
          <ReduxProvider>
            <StoreUser />
            <NextTopLoader color="#1D4ED8" />
            <Toaster position="top-center"
              toastOptions={{
                style: {
                  background: '#374151',
                  color: '#fff',
                  fontSize: '14px',
                  borderRadius: '10px',
                  padding: '5px 10px',
                }
              }}
            />
            {children}
          </ReduxProvider>
        </TranstackQueryProvider>
      </body>
    </html>
  );
}
