import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import { Toaster } from "react-hot-toast";
import TranstackQueryProvider from "@/providers/tanstack-query-provider";
import ReduxProvider from "@/lib/ReduxProvider";
import StoreUser from '@/components/StoreUser'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranstackQueryProvider>
          <ReduxProvider>
            <Toaster />
            <StoreUser />
            {children}
          </ReduxProvider>
        </TranstackQueryProvider>
      </body>
    </html>
  );
}
